### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by davewatson91** [cdmonk/esphome_ArlecSmartGlobe#2]
Mate, just wanted to say thankyou! 

Not entirely sure how I managed to google-fu my way to your git, but I've used this succesfully with the Brilliant bulbs from Bunnings/Officeworks. - Not sure if you care, but I reckon it would be worth getting your repo linked on the https://www.esphome-devices.com/ list, and add the additional devices. Happy to help if you'd like? 

Thanks again!

**Comment by cdmonk** [comment]
Hi Dave

Glad that it helped you. I started working on this after I bought some from Bunnings and they didn't with with Esphome. 

My implementation has a problem that I gave up trying to resolve as this it a MUCH better implementation that does not have the issue.

https://github.com/ssieb/custom_components/tree/master/cwww2

**Comment by davewatson91** [comment]
Thanks so much for the reply! 

Do appreciate the work you've put in!
